services:
  - docker

language: python

env:
  global:
    - BH_OPENMP_PROF=true
    - BH_OPENMP_VOLATILE=true
    - BH_OPENCL_PROF=true
    - BH_OPENCL_VOLATILE=true
    - TEST_RUN="/bohrium/test/python/run.py /bohrium/test/python/tests/test_*.py"
    - BENCHMARK_RUN="/bohrium/test/python/numpytest.py --file test_benchmarks.py"

script:
  - env | grep -E "BH_|_RUN|_EXEC" | sort > .env-file
  - cat .env-file
  - docker pull bohrium/bohrium:latest
  - docker run -t --env-file .env-file bohrium/bohrium

jobs:
  include:
    - stage: build docker image
      script:
        - docker login -u="$DOCKER_USER" -p="$DOCKER_PASSWORD"
        - docker build -t bohrium/bohrium -f package/docker/bohrium.dockerfile .
        - docker push bohrium/bohrium

    - stage: verify
    # Test suite
      env: PY_EXEC="python2.7" BH_STACK=openmp TEST_EXEC="$PY_EXEC $TEST_RUN"
    - env: PY_EXEC="python2.7" BH_STACK=opencl TEST_EXEC="$PY_EXEC $TEST_RUN"
    - env: PY_EXEC="python2.7" BH_STACK=openmp BH_OPENMP_MONOLITHIC=true TEST_EXEC="$PY_EXEC $TEST_RUN"
    - env: PY_EXEC="python2.7" BH_STACK=proxy_opencl TEST_EXEC="/usr/bin/bh_proxy_backend -a localhost -p 4200 & $PY_EXEC /bohrium/test/python/run.py /bohrium/test/python/tests/test_!(nobh).py"
    - env: PY_EXEC="python3.5" BH_STACK=openmp TEST_EXEC="$PY_EXEC $TEST_RUN"
    - env: PY_EXEC="python3.5" BH_STACK=opencl TEST_EXEC="$PY_EXEC $TEST_RUN"

    # Benchmarks
    - env: PY_EXEC="python2.7" BH_STACK=openmp TEST_EXEC="$PY_EXEC $BENCHMARK_RUN"
    - env: PY_EXEC="python2.7" BH_STACK=opencl TEST_EXEC="$PY_EXEC $BENCHMARK_RUN"
    - env: PY_EXEC="python3.5" BH_STACK=openmp TEST_EXEC="$PY_EXEC $BENCHMARK_RUN"
    - env: PY_EXEC="python3.5" BH_STACK=opencl TEST_EXEC="$PY_EXEC $BENCHMARK_RUN"

notifications:
  slack: bohrium:BCAEW8qYK5fmkt8f5mW95GUe
